- name: Check logstash downloaded
  stat:
    path: /tmp/logstash-7.6.2.rpm
  register: logstash_result
  tags: server



- name: Download elasticsearch
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-x86_64.rpm
    dest: "/tmp/"
  when: not es_result.stat.exists
  tags: server

- name: Download logstash
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-7.6.2.rpm
    dest: "/tmp/"
  when: not logstash_result.stat.exists
  tags: server


  tags: server





  tags: copy, server


  tags: copy, server

- name: Copy files to remote
  copy:
    src: /tmp/kibana-7.6.2-x86_64.rpm
    dest: /tmp/kibana-7.6.2-x86_64.rpm
  tags: copy, server
