- name: Copy logstash yum repo file
  copy:
    src=logstash.repo
    dest=/etc/yum.repos.d/logstash.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install logstash rpms
  yum:
    name: logstash
    state: latest
  become: true

- name: Copy logstash configuration
  template:
    src=logstash.conf.j2
    dest=/etc/logstash/conf.d/logstash.conf
    owner=logstash
    group=logstash
    mode=0644
  become: true

- name: Ensure logstash systemd unit file is present
  copy:
    src=logstash.service
    dest=/etc/systemd/system/logstash.service
    owner=root
    group=root
    mode=0644
    force=no
  register: logstash_unit_copied
  become: true

- name: Reload Systemd if we copied in logstash.service unit file
  command: systemctl daemon-reload
  when: logstash_unit_copied != 0
  become: true

- name: Restart logstash server
  command: systemctl restart logstash.service
  become: true
