
- name: Check filebeat downloaded
  stat:
    path: /tmp/filebeat-7.6.2-x86_64.rpm
  register: filebeat_result
  delegate_to: 127.0.0.1

- name: Download filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-7.6.2-x86_64.rpm
    dest: "/tmp/"
  when: not filebeat_result.stat.exists
  delegate_to: 127.0.0.1

- name: Copy files to remote
  copy:
    src: /tmp/filebeat-7.6.2-x86_64.rpm
    dest: /tmp/filebeat-7.6.2-x86_64.rpm
  delegate_to: 127.0.0.1
  
- name: Copy elasticsearch yum repo file
  copy:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install elasticsearch and openjdk
  yum:
    name: [filebeat]
    enablerepo: elastic-7.x
    state: latest
  become: true
  register: installbeat

- name: Copy templated elasticsearch.yml
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=elasticsearch
    mode=0660
  become: true
  ignore_errors: true

# this seems like a packaging bug for 6.x
- name: Create log directory structure for ES
  file:
    path: /usr/share/elasticsearch/logs
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755

# another packaging bug, this should be done by RPM
- name: Create datadir for elasticsearch
  file:
    path: /usr/share/elasticsearch/data
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755

- name: Start or restart elasticsearch service
  command: systemctl restart elasticsearch.service
  ignore_errors: true
  become: true
  when: installes.changed

- name: Port check for elasticsearch. Wait until port is reachable
  wait_for:
    port: "{{ elastic_port }}"
    delay: 5
  retries: 5

- name: Setup elasticsearch service to autostart
  service: name=elasticsearch state=started enabled=true
  become: true
